# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_dca.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_dca(object):
    def setupUi(self, add_dca):
        add_dca.setObjectName("add_dca")
        add_dca.resize(320, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_dca.sizePolicy().hasHeightForWidth())
        add_dca.setSizePolicy(sizePolicy)
        add_dca.setMinimumSize(QtCore.QSize(320, 160))
        add_dca.setMaximumSize(QtCore.QSize(320, 160))
        self.formLayoutWidget = QtWidgets.QWidget(add_dca)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 301, 124))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.add_dca_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.add_dca_layout.setContentsMargins(0, 0, 0, 0)
        self.add_dca_layout.setObjectName("add_dca_layout")
        self.base_currency_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.base_currency_label.setFont(font)
        self.base_currency_label.setObjectName("base_currency_label")
        self.add_dca_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.base_currency_label)
        self.base_currency_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.base_currency_input.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.base_currency_input.setFont(font)
        self.base_currency_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.base_currency_input.setMaxLength(4)
        self.base_currency_input.setAlignment(QtCore.Qt.AlignCenter)
        self.base_currency_input.setObjectName("base_currency_input")
        self.add_dca_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.base_currency_input)
        self.quote_currency_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quote_currency_label.setFont(font)
        self.quote_currency_label.setObjectName("quote_currency_label")
        self.add_dca_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.quote_currency_label)
        self.quote_currency_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.quote_currency_input.setFont(font)
        self.quote_currency_input.setText("")
        self.quote_currency_input.setMaxLength(4)
        self.quote_currency_input.setAlignment(QtCore.Qt.AlignCenter)
        self.quote_currency_input.setObjectName("quote_currency_input")
        self.add_dca_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quote_currency_input)
        self.quote_amount_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quote_amount_label.setFont(font)
        self.quote_amount_label.setObjectName("quote_amount_label")
        self.add_dca_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.quote_amount_label)
        self.quote_amount_input = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.quote_amount_input.setFont(font)
        self.quote_amount_input.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhNoPredictiveText)
        self.quote_amount_input.setAlignment(QtCore.Qt.AlignCenter)
        self.quote_amount_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.quote_amount_input.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.quote_amount_input.setMinimum(1)
        self.quote_amount_input.setMaximum(100000000)
        self.quote_amount_input.setSingleStep(1)
        self.quote_amount_input.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.quote_amount_input.setProperty("value", 1)
        self.quote_amount_input.setObjectName("quote_amount_input")
        self.add_dca_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.quote_amount_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_add_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.cancel_add_button.setDefault(False)
        self.cancel_add_button.setObjectName("cancel_add_button")
        self.horizontalLayout.addWidget(self.cancel_add_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.confirm_add_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.confirm_add_button.setDefault(True)
        self.confirm_add_button.setObjectName("confirm_add_button")
        self.horizontalLayout.addWidget(self.confirm_add_button)
        self.add_dca_layout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.add_dca_layout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.add_dca_layout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.add_dca_layout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem3)

        self.retranslateUi(add_dca)
        QtCore.QMetaObject.connectSlotsByName(add_dca)

    def retranslateUi(self, add_dca):
        _translate = QtCore.QCoreApplication.translate
        add_dca.setWindowTitle(_translate("add_dca", "Add DCA Purchase"))
        self.base_currency_label.setText(_translate("add_dca", "Base Currency (Crypto):"))
        self.base_currency_input.setPlaceholderText(_translate("add_dca", "BTC/ETH/ADA/etc."))
        self.quote_currency_label.setText(_translate("add_dca", "Quote Currency (Fiat):"))
        self.quote_currency_input.setPlaceholderText(_translate("add_dca", "USD/EUR/GBP/etc."))
        self.quote_amount_label.setText(_translate("add_dca", "Quote Currency Invested:"))
        self.quote_amount_input.setSuffix(_translate("add_dca", ".00"))
        self.quote_amount_input.setPrefix(_translate("add_dca", "$"))
        self.cancel_add_button.setText(_translate("add_dca", "Cancel"))
        self.confirm_add_button.setText(_translate("add_dca", "Add DCA Purchase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_dca = QtWidgets.QWidget()
    ui = Ui_add_dca()
    ui.setupUi(add_dca)
    add_dca.show()
    sys.exit(app.exec_())

